Kontakty

FOTO                            FOTO
Radek Novotný                    Jana Kasardová
obchodní ředitel                    zákaznická podpora
Tel.: +420 731 539 582
E-mail: radek.novotny@vinotékaolvi.cz            E-mail: info@vinotekaolvi.cz


Fakturační údaje:
www.vinotekaolvi.cz
IČ: 47649992
Sídlo firmy:
Ratenice 181
289 11 Pečky

Bankovní spojení:
CZK v České republice
2300470476/2010

EUR ve Slovenské republice
2300470476/8330

Jiné měny a mezinárodní platby:
IBAN:CZ9420100000002300470476
SWIFT/BIC KÓD: FIOBCZPPXXX


Kamnenný obchod:

Vinotéka OLVI
Palachova 424/16
(naproti  ZŠ  T.G.Masaryka)
290 01 Poděbrady
