{*
* dont forget is 2 version of same text desktop and mobile
*}
{block|texy}
Kontakty
========
{if $isMobile}
.[table]
| <img src="/images/mini/kontakty-radek.jpg" alt="Radek" class="img-responsive" /> |
| **Radek Novotný** |
| obchodní ředitel |
| <a href="tel:+420731539582">+420 731 539 582</a> |
| radek.novotny@vinotekaolvi.cz |

.[table]
| <img src="/images/mini/kontakty-jana.jpg" alt="Jana" class="img-responsive" /> |
| **Jana Kasardová** |
| zákaznická podpora |
| |
| info@vinotekaolvi.cz|


{else}
.[table]
| 		| <img src="/images/kontakty-radek.jpg" alt="Radek" width="300px" /> | 	| <img src="/images/kontakty-jana.jpg" alt="Jana" width="300px" /> |
| 		| **Radek Novotný** | 											| **Jana Kasardová** |
|Pozice | obchodní ředitel | 											| zákaznická podpora |
|Telefon| <a href="tel:+420731539582">+420 731 539 582</a> | 			| |
| Email | radek.novotny@vinotekaolvi.cz | 								| info@vinotekaolvi.cz|
{/if}


Fakturační údaje:
-----------------
www.vinotekaolvi.cz
 IČ: 47649992
 DIC CZ7203100861

**Bankovní spojení**
 CZK v České republice
 2300470476/2010

EUR ve Slovenské republice
 2300470476/8330

Jiné měny a mezinárodní platby:
 IBAN:CZ9420100000002300470476
 SWIFT/BIC KÓD: FIOBCZPPXXX

{/block}