{block|texy}
Kontakty
========

.[table]
| | Radek Novotný | 							| Jana Kasardová |
|Pozice | obchod | 								| zákaznická podpora |
|Telefon|  +420 731 539 582 | 					| |
| Email | radek.novotny@vinotékaolvi.cz | 		| info@vinotekaolvi.cz|

Fakturační údaje:
-----------------
www.vinotekaolvi.cz
 IČ: 47649992
 DIC CZ7203100861

**Bankovní spojení**
 CZK v České republice
 2300470476/2010

EUR ve Slovenské republice
 2300470476/8330

Jiné měny a mezinárodní platby:
 IBAN:CZ9420100000002300470476
 SWIFT/BIC KÓD: FIOBCZPPXXX

{/block}