O nás
=====

**Máme rádi dobrou a kvalitní kuchyni a k tomu patří i dobré a kvalitní víno.**

Rádi zkoušíme nové recepty a chutě, a proto se s vámi chceme podělit o naše produkty.
Zabýváme se prodejem olejů lisovaných za studena, které jsou vyrobeny v Rakousku a prodejem moravských sudových a lahvových vín.

Oleje i vína si můžete zakoupit v našem kamenném obchodě v Poděbradech ve  VINOTÉCE OLVI.

Budeme se těšit na Vaši návštěvu!
Radek a Jana
