{block|texy}
== Recepty

== O dýňovém oleji
Dýňový olej se vyrábí lisováním za studena ze semínek dýně - Tykve obecné. Semínka mají bílou barvu, po odstranění slupky se však objevuje typická nazelenalá barva.

[* /images/ilustrace-1.jpg .(alt ilustrace) *]

Foto z webu Pelzmann

Dnes je dýně a dýňový olej oblíbený především v rakouském Štýrsku. Zde má výroba dýňového oleje dlouholetou tradici, olej se zde vyrábí již přes tři sta let a označení Štýrský dýňový olej se stalo dokonce chráněnou známkou.

[* /images/ilustrace-2.jpg .(alt ilustrace) *]

Foto z webu Pelzmann

Dýňový olej má svou specifickou tmavě –zelenou barvu s hustší konzistencí a upoutá také svou jemnou oříškovou chutí, blahodárným složením a širokým využitím ve zdravé kuchyni.


[* /images/ilustrace-3.jpg .(alt ilustrace) *]

Foto z webu Pelzmann

== Dýňová semínka

[* /images/ilustrace-4.jpg .(alt ilustrace) *]

Foto stažené z obrázků na google…

Semínka, která z dýní odstraníme, bychom rozhodně neměli vyhazovat. Podobně jako všechna jedlá semena jsou totiž zásobárnou výživných a léčivých látek.

Dýňová semínka se od pradávna využívala jako prostředek proti parazitům, obsahují totiž zatím nezjištěnou složku, která zabraňuje zachycení parazitů ve střevech a napomáhá jejich vypuzování.

Mnohem významnějším je obsah cenných nenasycených mastných kyselin, především omega-3, ale také omega-6, které snižují cholesterol, vysoký tlak a riziko infarktu i mrtvice.

Semínka jsou dobrým zdrojem vitamínů A,E a kyseliny listové, najdeme v nich také celou řadu minerálů:
jeden šálek (64g) dýňových semínek obsahuje:
zhruba 40% doporučené denní dávky (DDD) zinku, 20% DDD mědi, 40% DDD hořčíku, 15% DDD manganu, 15% DDD draslíku a 15% DDD železa.

Dýňová semínka jsou také zdrojem přírodních hormonálně účinnýh látek a dalších složek, které zpomalují stárnutí a působí proti degenerativním procesům.


Kdy jsou semínka prospěšná:

* při zvětšení prostaty (brzdí její růst)
* snižují krevní tlak
* zvyšují prospěšný HDL cholesterol
* snižují výskyt návalů, bolesti hlavy a kloubů
* při ledvinových kamenech ze šťavelanu vápenatého
* při onemocnění srdečně-cévního systému a jater (ve směsi s lněnými semínky mají ochranný vliv na srdce, cévy a játra)
* při nespavosti (obsahují velké množství aminokyseliny tryptofan, což je prekurzor serotoninu, který je večer přeměňován na melatonin – „hormon spánku“
* při kožních onemocněních (jsou nejlepším zdrojem zinku potřebného pro stavbu kostí a vůbec všech tkání v těle a důležitého pro naši imunitu)
* při chronickém únavovém syndromu (kvůli vysokému obsahu hořčíku)


Všestranné využití dýňových semínek v kuchyni:

* dýňová semena můžeme přidávat do polévek, do ovocných i zeleninových salátů, do doma pečeného chleba či do moučníků
* dýňovými semeny můžeme v těstech na moučníky nahradit vlašské ořechy
* rybí filety nebo kuřecí řízky před smažením můžeme obalit ve směsi drcených dýňových a slunečnicových semen
* nasekaná dýňová semena můžeme přidávat do drobenky na slané koláče


== Pyré z dýňových semínek:

Pražená dýňová semínka rozmixujeme s limetkovou šťávou, česnekem, koriandrem a trochu oleje z dýňových semen. Pyré využijeme jako omáčku na těstoviny, ryby nebo kuře.


== Chléb z dýňového oleje

[* /images/ilustrace-5.jpg .(alt ilustrace) *]

Foto z webu pelzmann

* 450 g špaldové mouky
* (můžete vyzkoušet např. 200 g žitné mouky a 250 g chlebové pšeničné mouky)
* 1 balíček sušených kvasnic
* 1 vrchovatá lžička soli
* 1 lžička kmínu
* 100 g dýňových (slaných) semínek
* 350 ml vlažné vody
* 3 lžíce štýrského dýňového oleje


Ve velké míse nejprve smícháme mouku se sušenými kvasnicemi, solí, kmínem a dýňovými  semínky. Pár dýňových semínek si necháme na ozdobu. Pak přidáme vlažnou vodu a dýňový olej a cca 10 min. hněteme. Těsto si můžete přendat na vál a můžete ho prohnětat ručně, pak těsto přikryjeme utěrkou a na 30 min. necháme odpočinout. Připravíme si plech s pečícím papírem nebo formu na chléb, kterou vyložíme pečícím papírem a vytvarované těsto přendáme na plech (do formy), chléb pomažte vodou a posypejte zbylými dýňovými semínky.
Troubu předehřejte na 220°C a vložte do ní chléb, doporučujeme umístit doprostřed trouby hrnek s vodou. Po 10 min. stáhněte teplotu na 180 °C a pečte cca 50 min.


Tvarohová pomazánka s dýňovým olejem

[* /images/ilustrace-5.jpg .(alt ilustrace) *]

* 250 g polotučného tvarohu
* cca 2 lžíce dýňového oleje
* 2 lžíce nasekanýh dýňových semínek
* sůl, pepř
* pár celých dýňových semínek
Do tvarohu zamíchejte dýňový olej, nasekaná dýňová semínka, osolte, opepřete a ozdobte celými dýňovými semínky. Výborně chutná s čerstvým chlebem z dýňového oleje.


Míchaná vejce s dýňovým olejem a semínky

[* /images/ilustrace-6.jpg .(alt ilustrace) *]

Foto z webu pelzmann – oříznout nápis dole

* 1/2 svazku petržele
* 1 lžička másla
* 40 g dýňových semínek
* 4 vejce
* 1 lžíce dýňového oleje
* sůl, pepř

Vejce rozklepneme do misky a pomocí vidličky je lehce rozmícháme, trochu osolíme a opepříme. Dýňová semínka nasekáme nahrubo a petrželku najemno. Na nepřilnavou (teflonovou) pánev dejte 1 lžíci dýňového oleje a jen mírně ho zahřejte, tak aby se dýňový olej nepřepaloval a zachovaly se všechny cenné vlastnosti. Nerezovou pánev naopak hodně rozpalte a pak do ní vlijte dýňový olej. Pak nasypte dýňová semínka a krátce orestujte, poté vlijte vaječnou směs a ihned míchejte. Přidejte petrželku. Nakonec vmíchejte čerstvé máslo – zjemní chuť a vejce zůstanou krásně krémová. Čím více másla, tím jemnější vejce.


== SALÁTOVÁ ZÁLIVKA

[* /images/ilustrace-7.jpg .(alt ilustrace) *]

Foto z webu pelzmann

* 1 lžíce oleje z vlašských ořechů
* 1 lžíce jablečného /nebo hruškového/ octa
* 1 lžíce dijonské hořčice
* 30 g kerblíku a petrželky
* 1 citron
* cca 1/8 l dýňového oleje
* trochu soli
* 2 cl bezinkového sirupu
* 1/16 l zeleninového vývaru

Smícháme hořčici s vychladlým zeleninovým vývarem  a oleji, dále přidáme bezinkový sirup, sůl, citron a jablečný ocet  nebo hruškový ocet a nakonec  přimícháme čerstvé bylinky. Marináda se hodí na jakýkoliv salát
Pozn.
Kerblík má delikátní chuť připomínající estragon nebo petržel. Francouzi ho přidávají především rybích pokrmům, ale i vaječným, drůbežímu masu i do salátových zálivek. Kerblík samotný je výborný ve smetanových polévkách a omáčkách, nebo s dušenou mrkví na másle.


== TĚSTOVINY S DÝŇOVÝM PESTEM

[* /images/ilustrace-8.jpg .(alt ilustrace) *]

Foto z webu pelzmann

* 60 g dýňových semínek
* 1/8 l dýňového oleje
* 30 g parmezánu vcelku
* 80 g listů polníčku
* sůl, pepř z mlýnku
* 400 g Pappardelle

Omyjeme 50 g polníčku, vysušíme a nasekáme nahrubo. Parmezán nastrouháme najemno. Dýňová semínka, dýňový olej, parmezán, polníček, sůl a pepř umixujeme v kuchyňském robotu nebo rozmělníme v hmoždíři. Pappardelle vaříme al dente, scedíme a ještě horké smícháme s pestem . Na ozdobu použijeme zbývající lístky polníčku.

== BÁBOVKA S DÝŇOVÝM OLEJEM

* 4 vejce
* 100 ml vody
* 1 balíček vanilkového cukru
* 100 ml dýňového oleje
* 100 g nasekaných dýňových semínek
* 150 g  cukru krystal
* 50 g cukru moučky
* 250 g špaldové mouky (nebo polohrubé mouky)
* ½ balíčku prášku do pečiva

Na ozdobu:
* rybízový nebo brusinkový džem
* šlehačka nebo zakysaná smetana

Vejce rozklepneme a oddělíme žloutky od bílků. Všechny sypké ingredience smícháme v míse. Přidáme čtyři žloutky, dýňový olej a vodu. Vše zamícháme. Z bílků ušleháme sníh a opatrně vmícháme do těsta. Podle chuti můžeme přidat dýňová semínka. Těsto nalijeme do vymazané a moukou vysypané formy. Bábovku vkládáme do předehřáté trouby a pečeme prvních 20 minut na 150 - 160 °C. Potom přidáme na 180 °C a dopékáme asi 20 - 30 minut. Zkusíme špejlí, jestli je uvnitř hotová.

Místo dýňových semínek a dýňového oleje můžete použít lískové ořechy a olej z lískových ořechů nebo můžete vyzkoušet i kombinaci vlašských ořechů a oleje z vlašských ořechů.

[* /images/ilustrace-9.jpg .(alt ilustrace) *]

Foto z webu pelzmann
{/block}
