{block|texy}
== Oleje

Nabízíme Vám oleje lisované za studena, které jsou vyrobeny v Rakousku.

Bez obav vyzkoušejte naše oleje a budete překvapeni. Vše, co umíte s olivovým olejem, dělejte s našimi oleji! Možná vám to pak bude chutnat ještě víc.

Střídání  olejů vám nejen zpestří  chuťové zážitky, ale také poskytne vašemu zdraví téměř vše, co potřebuje, naučíme vás naše oleje používat v teplé i studené kuchyni, podle našich vyzkoušených receptů.

Nebojte se experimentovat!
S chutí do toho!


== Štýrský dýňový olej 250 ml  269,-Kč

Tmavě zelený dýňový olej je husté konzistence a má chuť po pražených oříšcích.
Díky oříškové chuti se hodí nejen do slaných, ale i sladkých pokrmů.
Olej z dýňových semínek je určen především k použití zastudena. Je výborný nejen do salátů, ale i na bylinkové brambory, sýry, masa, rizota, těstoviny, vaječnou omeletu, do pomazánek nebo krémových polévek.
Nebo si jím jen tak ochuťte palačinky, ovesnou kaši či zmrzlinový pohár.

Po otevření doporučujeme uchovávat  v chladničce.
Nepoužívejte na smažení nebo fritování.
Chraňte před světlem a neuchovávejte při vyšších teplotách než je pokojová.


== Dýňový olej 250 ml  229,-Kč

Tmavě zelený dýňový olej je husté konzistence a má chuť po pražených oříšcích.
Díky oříškové chuti se hodí nejen do slaných, ale i sladkých pokrmů.
Olej z dýňových semínek je určen především k použití zastudena. Je výborný nejen do salátů, ale i na bylinkové brambory, sýry, masa, rizota, těstoviny, vaječnou omeletu, do pomazánek nebo krémových polévek.
Nebo si jím jen tak ochuťte palačinky, ovesnou kaši či zmrzlinový pohár.

100% čistý

Po otevření doporučujeme uchovávat  v chladničce.
Nepoužívejte na smažení nebo fritování.
Chraňte před světlem a neuchovávejte při vyšších teplotách než je pokojová.


== Dýňový olej 500 ml  369,-Kč

Tmavě zelený dýňový olej je husté konzistence a má chuť po pražených oříšcích.
Díky oříškové chuti se hodí nejen do slaných, ale i sladkých pokrmů.
Olej z dýňových semínek je určen především k použití zastudena. Je výborný nejen do salátů, ale i na bylinkové brambory, sýry, masa, rizota, těstoviny,vaječnou omeletu, do pomazánek nebo krémových polévek.
Nebo si jím jen tak ochuťte palačinky, ovesnou kaši či zmrzlinový pohár.


100% čistý

Po otevření doporučujeme uchovávat  v chladničce.
Nepoužívejte na smažení nebo fritování.
Chraňte před světlem a neuchovávejte při vyšších teplotách než je pokojová.


== Salátový olej 500 ml  189,-Kč

Má široké využití na přípravu salátů všeho druhu ,obsahuje  vysoce kvalitní řepkový olej a dýňový olej.

Po otevření doporučujeme uchovávat  v chladničce.
Nepoužívejte na smažení nebo fritování.
Chraňte před světlem a neuchovávejte při vyšších teplotách než je pokojová.


== Salátový olej 1000 ml  219,-Kč

Má široké využití na přípravu salátů všeho druhu , obsahuje  vysoce kvalitní řepkový olej a dýňový olej.

Po otevření doporučujeme uchovávat  v chladničce.
Nepoužívejte na smažení nebo fritování.
Chraňte před světlem a neuchovávejte při vyšších teplotách než je pokojová.


== Sezamový olej 250 ml  209,-Kč

Hodí se na přípravu ryb, drůbeže a zeleniny, dodává jídlu jemnou orientální chuť. Má vysoký obsah nenasycených mastných kyselin cenných pro zdravou výživu.

za studena lisovaný
Po otevření doporučujeme uchovávat  v chladničce.
Nepoužívejte na smažení nebo fritování.
Chraňte před světlem a neuchovávejte při vyšších teplotách než je pokojová.

== Olej z vlašských ořechů 250 ml  209,-Kč

Výborný na saláty, na dochucení studené kuchyně (např. studeného masa), ale i moučníků, dezertů, dortů nebo na dochucení pečiva.

Po otevření doporučujeme uchovávat  v chladničce.
Nepoužívejte na smažení nebo fritování.
Chraňte před světlem a neuchovávejte při vyšších teplotách než je pokojová.


== Olej z lískových ořechů 250 ml  249,-Kč

Ideální využití tohoto oleje je na pečení koláčů, na přípravu dezertů, na vylepšení chuti dortů, ale i salátů, nebo na přípravu domácího müsli anebo si jím jen tak pokapejte zmrzlinu.

Po otevření doporučujeme uchovávat  v chladničce.
Nepoužívejte na smažení nebo fritování.
Chraňte před světlem a neuchovávejte při vyšších teplotách než je pokojová.


== Štýrský jablečný ocet 750 ml  144,-Kč

Vyroben z přírodní jablečné šťávy, nefiltrovaný. Tento jablečný ocet má výrazně ovocně kyselou chuť, hodí se do salátů, dresinků a k přípravě pochutin z uzených a masných výrobků.

stupeň kyselosti 6%
Chraňte před světlem a neuchovávejte při vyšších teplotách než je pokojová.


== Štýrský hruškový ocet 500 ml  169,-Kč

Vyroben z přírodní hruškové šťávy, nefiltrovaný. Vyzkoušejte v kombinaci s některým z olejů např. s dýňovým olejem nebo olejem z vlašských ořechů jako zálivku na saláty, na ochucení zeleninových pokrmů, drůbeže, zvěřin, ale i čočky anebo polévek. Hruškový ocet Vás překvapí svou příjemnou ovocnou chutí.

stupeň kyselosti 5%
Chraňte před světlem a neuchovávejte při vyšších teplotách než je pokojová.
{/block}