{block|texy}
<?php
$days = [
	1 => ['Pondělí', '14:00 – 18:00'], //Monday
	2 => ['Úterý', '14:00 – 18:00'],
	3 => ['Středa', '14:00 – 18:00'],
	4 => ['Čtvrtek', '14:00 – 18:00'],
	5 => ['Pátek', '14:00 – 18:00'],
	6 => ['Sobota', '9:00 – 12:00'],
	0 => ['Neděle', 'Zavřeno'] //Sunday
];
?>

OTEVÍRACÍ DOBA
==============
.[table]
|----------------------
| Den | Otevírací doba
|----------------------
{foreach $days AS $key => $val}
{if date('w') == $key}
| **{$val[0]}** | **{$val[1]}**
{else}
| {$val[0]} | {$val[1]}
{/if}
{/foreach}

{/block}