<?php
$days = [
	1 => ['Pondělí', '13:00 – 19:00'], //Monday
	2 => ['Úterý', '13:00 – 19:00'],
	3 => ['Středa', '13:00 – 19:00'],
	4 => ['Čtvrtek', '13:00 – 19:00'],
	5 => ['Pátek', '13:00 – 18:00'],
	6 => ['Sobota', '13:00 – 19:00'],
	7 => ['Neděle', 'Zavřeno'] //Sunday
];
?>
OTEVÍRACÍ DOBA
==============
.[table]
|----------------------
| Den | Otevírací doba
|----------------------
{foreach $days AS $key => $val}
{if date('w') == $key}
| **{$val[0]}** | **{$val[1]}**
{else}
| {$val[0]} | {$val[1]}
{/if}
{/foreach}
