== Víno

Vážení milovníci vín,
budeme rádi, když si najdete čas a cestu do naší vinotéky v Poděbradech a přijdete ochutnat naše moravská vína.

Nabízíme Vám 11 druhů moravského sudového vína z Rodinného vinařství Průdek-Rakvice.
V naší vinotéce Vám stočíme libovolné množství do přinesených nádob, nebo do našich PET lahví.
== Sudová vína:
| Veltlínské zelené | bílé | suché | 1l | 49,- Kč
| Ryzlink vlašský | bílé | suché | 1l | 53,- Kč
| Chardonnay | bílé | suché | 1l | 57,- Kč
| Rulandské šedé | bílé | suché | 1l | 58,- Kč
| Tramín červený | bílé | polosuché | 1l | 62,- Kč
| Pálava | bílé | polosuché | 1l | 62,- Kč
| Cabernet Moravia | rosé | polosuché | 1l | 56,- Kč
| Dornfelder | červené | suché | 1l | 55,- Kč
| Modrý Portugal | červené | suché | 1l | 53,- Kč
| Zweigeltrebe | červené | suché | 1l | 56,- Kč
| Frankovka | červené | suché | 1l | 49,- Kč

| PET lahev čirá | 1l | 5,-Kč
| PET lahev zelená | 1l | 5,-Kč
| PET lahev zelená | 2l | 6,-Kč

Nabízíme také široký sortiment lahvových vín, od ověřených vinařů z Moravy. Můžete si u nás vybrat od bílých lehkých vín přes růžová až k červeným těžším vínům. Najdete u nás vína nejen pro krásný večer, ale vyberete i luxusní víno jako dárek.
Rádi Vám poradíme a doporučíme osvědčená vína pro Vámi zamýšlenou příležitost.
Těšíme se na Vaši návštěvu!
Lahvová vína z Moravy:
* Vinařství Průdek-Rakvice
* Vinařství Veverka-Čejkovice
* Vinařství Tanzberg-Mikulov
* Vinařství Morávia Víno-Prušánky


== CENÍK

## RODINNÉ VINAŘSTVÍ PRŮDEK - RAKVICE

| André | 2011 | pozdní sběr | červené | suché | 170,-Kč
| Aurelius | 2012 | pozdní sběr | bílé | suché | 140,-Kč
| Cabernet Moravia | 2011 | pozdní sběr | červené | suché | 170,-Kč
| Cabernet Sauvignon | 2012 | pozdní sběr | rosé | polosuché | 140,-Kč
| Chardonnay | 2011 | moravské zemské víno | bílé | polosuché | 170,-Kč
| Rulandské modré | 2011 | moravské zemské víno | červené | suché | 170,-Kč
| Sylvánské zelené | 2012 | pozdní sběr | bílé | suché | 140,-Kč
| Tramín červený | 2011 | pozdní sběr | bílé | polosuché | 170,-Kč

== VINAŘSTVÍ TANZBERG - MIKULOV

| Cabernet Sauvignon - Turold | 2008 | pozdní sběr | červené | suhé | 242,-Kč
| Frankovka rosé - Turold | 2012 | pozdní sběr | rosé | polosuché | 190,-Kč
| Frankovka+Merlot | 2008 | jakostní | červené | suché | 182,-Kč
| Chardonnay -Valtická | 2011 | pozdní sběr | bílé | suché | 168,-Kč
| Merlot - Pod Pálavou | 2009 | výběr z hroznů | červené | suché | 230,-Kč
| Pinot Grips - Turold | 2010 | pozdní sběr | bílé | suché | 224,-Kč
| Ryzlink vlašský - Goldhamer | 2012 | pozdní sběr | bílé | suché | 190,-Kč

== VINAŘSTVÍ VEVERKA -ČEJKOVICE

| Alibernet | 2011 | jakostní | červené | suché | 173,-Kč
| Frankovka | 2011 | pozdní sběr | červené | suché | 132,-Kč
| Hibernal | 2011 | výběr z hroznů | bílé | polosladké | 230,-Kč
| Neronet | 2011 | pozdní sběr | červené | suché | 168,-Kč
| Pálava | 2012 | pozdní sběr | bílé | polosladké | 187,-Kč
| Rulandské šedé | 2011 | pozdní sběr | bílé | polosladké | 202,-Kč
| Ryzling vlašský BIO | 2011 | pozdní sběr | bílé | polosuché | 173,-Kč

== VINAŘSTVÍ MORÁVIA VÍNO - PRUŠÁNKY

| Portugal modrý | 2011 | pozdní sběr | červené | suché | 173,-Kč
| Rulandské šedé | 2011 | pozdní sběr | bílé | suché | 178,-Kč
| Rulandské modré | 2010 | pozdní sběr | červené | suché | 187,-Kč
| Ryzling rýnský | 2011 | pozdní sběr | bílé | polosuché | 175,-Kč
| Sauvignon | 2011 | výběr z hroznů | bílé | polosuché | 189,-Kč
| Svatovavřinecké | 2011 | výběr z hroznů | červené | suché | 205,-Kč
